services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: baytib_keycloak
    command: start-dev
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - baytic-network

  postgres:
    image: postgres:latest
    container_name: baytib_postgres
    environment:
      - POSTGRES_DB=baytic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - baytic-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "baytib_pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - baytic-network

  bayticapi:
    image: bayticapi
    container_name: baytib_api
    build:
      context: .
      dockerfile: src/Baytic.Api/Dockerfile
    ports:
      - 5003:5003
    depends_on:
      - postgres
      - keycloak
    networks:
      - baytic-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003

  baytic-web:
    image: baytic-web:latest
    container_name: baytib_web
    build:
      context: ./src/baytic-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - bayticapi
      - keycloak
    networks:
      - baytic-network

networks:
  baytic-network:
    name: baytic-network
    driver: bridge

volumes:
  keycloak_data:
    name: keycloak_data
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data