services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    command: start-dev
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - baytic-network

networks:
  baytic-network:
    name: baytic-network
    driver: bridge

volumes:
  keycloak_data:
